pages:
  - pages/index/index
  - pages/samples/basic/basic
  - pages/samples/comps/comps
  - pages/samples/waterfall/waterfall
window:
  backgroundTextStyle: light
  navigationBarBackgroundColor: '#fff'
  navigationBarTitleText: Weixin
  navigationBarTextStyle: black
style: v2
sitemapLocation: sitemap.json
