pages:
  - pages/index/index
  - pages/waterfall/waterfall
window:
  backgroundTextStyle: light
  navigationBarBackgroundColor: '#fff'
  navigationBarTitleText: Weixin
  navigationBarTextStyle: black
style: v2
sitemapLocation: sitemap.json
